extern int mikfx_init(void);
extern void mikfx_bye(void);
extern void mikfx_boing(const int l, const int r);
extern void mikfx_frappe(const int l, const int r);
extern void mikfx_debut_match(void);
extern void mikfx_engagement(void);
extern void mikfx_clapclap(void);
extern void mikfx_avant_engagement(const int l, const int r);
extern void mikfx_get_bonus(const int l, const int r);
extern void mikfx_got_bonus(const int l, const int r);
extern void mikfx_end_bonus(const int l, const int r);
extern void mikfx_alea(void);
extern void mikfx_bfork(void);
extern void mikfx_descotche(const int l, const int r);
extern void mikfx_bip(void);
extern void mikfx_glue(void);
extern void mikfx_lazer(const int l, const int r);
extern void mikfx_softzak(void);
extern void mikfx_endmatch(void);
